config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'users#dashboard'

  get '/upload_data', to: 'files#new', as: :file_upload

  post '/upload', to: 'files#upload', as: :upload_file

  get '/dashboard', to: 'users#dashboard', as: :dashboard

  get '/graphs/floor_data', to: 'graphs#floor_data', defaults: { format: 'json' }

  get '/graphs/step_data', to: 'graphs#step_data', defaults: { format: 'json' }

  get '/graphs/km_data', to: 'graphs#km_data', defaults: { format: 'json' }

  get '/graphs/calorie_data', to: 'graphs#calorie_data', defaults: { format: 'json' }

  get '/graphs/activity_data', to: 'graphs#activity_data', defaults: { format: 'json' }

  get '/graphs/sleep_data', to: 'graphs#sleep_data', defaults: { format: 'json' }

  get '/graphs/awakening_data', to: 'graphs#awakening_data', defaults: { format: 'json' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sleeps, dependent: :destroy
  has_many :activities, dependent: :destroy

  validates :name, presence: true, length: { in: 2..20 }

  NO_FLOORS_MESSAGE = "No floors recorded"
  NO_KM_MESSAGE = "No kilometres recorded"
  NO_STEPS_MESSAGE = "No steps recorded"
  NO_ACTIVITY_MESSAGE = "No activity recorded"
  NO_CALORIES_MESSAGE = "No calories recorded"

  def lifetime_floors
    activities.sum(&:floors)
  end

  def lifetime_kilometres
    activities.sum(&:distance)
  end

  def lifetime_steps
    activities.sum(&:steps)
  end

  def lifetime_calories_burned
    activities.sum(&:calories_burned)
  end

  def lifetime_minutes_asleep
    sleeps.sum(&:minutes_asleep)
  end

  def lifetime_minutes_awake
    sleeps.sum(&:minutes_awake)
  end

  def lifetime_awakenings
    sleeps.sum(&:number_of_awakenings)
  end

  def lifetime_time_in_bed
    sleeps.sum(&:time_in_bed)
  end

  def calculate_average(sum_of_values, total_number)
    if sum_of_values > 0
      (sum_of_values / total_number).round(2)
    else
      sum_of_values
    end
  end

  def average_calories_burned
    calculate_average(lifetime_calories_burned, activities.count)
  end

  def average_floors
    calculate_average(lifetime_floors, activities.count)
  end

  def average_kilometres
    calculate_average(lifetime_kilometres, activities.count)
  end

  def average_minutes_asleep
    calculate_average(lifetime_minutes_asleep, sleeps.count)
  end

  def average_minutes_awake
    calculate_average(lifetime_minutes_awake, sleeps.count)
  end

  def average_awakenings
    calculate_average(lifetime_awakenings, sleeps.count)
  end

  def average_time_in_bed
    calculate_average(lifetime_time_in_bed, sleeps.count)
  end

  def average_steps
    calculate_average(lifetime_steps, activities.count)
  end

  def highest_floors
    activity = highest_floor_activity

    activity ? activity.floors : 0
  end

  def highest_floor_date
    activity = highest_floor_activity

    activity ? activity.date : NO_FLOORS_MESSAGE
  end

  def highest_kilometres
    activity = highest_kilometre_activity

    activity ? activity.distance : 0
  end

  def highest_kilometre_date
    activity = highest_kilometre_activity

    activity ? activity.date : NO_KM_MESSAGE
  end

  def highest_steps
    activity = highest_step_activity

    activity ? activity.steps : 0
  end

  def highest_step_date
    activity = highest_step_activity

    activity ? activity.date : NO_STEPS_MESSAGE
  end

  def highest_calories_burned
    activity = highest_calories_burned_activity

    activity ? activity.calories_burned : 0
  end

  def highest_calories_burned_date
    activity = highest_calories_burned_activity

    activity ? activity.date : NO_CALORIES_MESSAGE
  end

  def lowest_floors
    activity = lowest_floor_activity

    activity ? activity.floors : 0
  end

  def lowest_floor_date
    activity = lowest_floor_activity

    activity ? activity.date : NO_FLOORS_MESSAGE
  end

  def lowest_steps
    activity = lowest_step_activity

    activity ? activity.steps : 0
  end

  def lowest_step_date
    activity = lowest_step_activity

    activity ? activity.date : NO_STEPS_MESSAGE
  end

  def lowest_kilometres
    activity = lowest_kilometre_activity

    activity ? activity.distance : 0
  end

  def lowest_kilometre_date
    activity = lowest_kilometre_activity

    activity ? activity.date : NO_KM_MESSAGE
  end

  def lowest_calories_burned
    activity = lowest_calories_burned_activity

    activity ? activity.calories_burned : 0
  end

  def lowest_calories_burned_date
    activity = lowest_calories_burned_activity

    activity ? activity.date : NO_CALORIES_MESSAGE
  end

  def highest_very_active_minutes
    very_active = highest_very_active_activity

    very_active ? very_active.minutes_very_active : 0
  end

  def highest_very_active_date
    very_active = highest_very_active_activity

    very_active ? very_active.date : NO_ACTIVITY_MESSAGE
  end

  def most_active_day
    activity = highest_active_activity

    activity ? activity.date : NO_ACTIVITY_MESSAGE
  end

  def least_active_day
    activity = highest_sedentary_activity

    activity ? activity.date : NO_ACTIVITY_MESSAGE
  end

  private

  def highest_floor_activity
    activities.max_by { |activity| activity.floors }
  end

  def highest_kilometre_activity
    activities.max_by { |activity| activity.distance }
  end

  def highest_step_activity
    activities.max_by { |activity| activity.steps }
  end

  def highest_calories_burned_activity
    activities.max_by { |activity| activity.calories_burned }
  end

  def lowest_floor_activity
    activities.min_by { |activity| activity.floors }
  end

  def lowest_step_activity
    activities.min_by { |activity| activity.steps }
  end

  def lowest_kilometre_activity
    activities.min_by { |activity| activity.distance }
  end

  def lowest_calories_burned_activity
    activities.min_by { |activity| activity.calories_burned }
  end

  def highest_very_active_activity
    activities.max_by { |activity| activity.minutes_very_active }
  end

  def highest_active_activity
    activities.max_by { |activity| activity.total_active_minutes }
  end

  def highest_sedentary_activity
    activities.max_by { |activity| activity.minutes_sedentary }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end
end

app/views/users/dashboard.html.erb
<h2>Dashboard for <%= current_user.name %></h2>

<%= link_to "Upload Data", file_upload_path, class: "button" %>

<h3>Lifetime Achievements</h3>
<p>Lifetime floors: <%= current_user.lifetime_floors %></p>
<p>Lifetime steps: <%= current_user.lifetime_steps %></p>
<p>Lifetime kilometres: <%= current_user.lifetime_kilometres %></p>
<p>Lifetime calories burned: <%= current_user.lifetime_calories_burned %></p>
<p>Lifetime minutes asleep: <%= current_user.lifetime_minutes_asleep %></p>

<h3>Floors</h3>
<svg class="floor-chart" width=960 height=400></svg>
<p>Average floors: <%= current_user.average_floors %></p>
<p>Highest floors: <%= current_user.highest_floors %> on <%= current_user.highest_floor_date %></p>
<p>Lowest floors: <%= current_user.lowest_floors %> on <%= current_user.lowest_floor_date %></p>

<h3>Steps</h3>
<svg class="step-chart" width=960 height=400></svg>
<p>Average steps: <%= current_user.average_steps %>
<p>Highest steps: <%= current_user.highest_steps %> on <%= current_user.highest_step_date %></p>
<p>Lowest steps: <%= current_user.lowest_steps %> on <%= current_user.lowest_step_date %></p>

<h3>Kilometres</h3>
<svg class="km-chart" width=960 height=400></svg>
<p>Average kilometres: <%= current_user.average_kilometres %></p>
<p>Highest kilometres: <%= current_user.highest_kilometres %> on <%= current_user.highest_kilometre_date %></p>
<p>Lowest kilometres: <%= current_user.lowest_kilometres %> on <%= current_user.lowest_kilometre_date %></p>

<h3>Calories Burned</h3>
<svg class="calorie-chart" width=960 height=400></svg>
<p>Average calories burned: <%= current_user.average_calories_burned %></p>
<p>Highest calories burned: <%= current_user.highest_calories_burned %> on <%= current_user.highest_calories_burned_date %></p>
<p>Lowest calories burned: <%= current_user.lowest_calories_burned %> on <%= current_user.lowest_calories_burned_date %></p>

<h3>Activity</h3>
<svg class="activity-chart-stacked" width=960 height=400></svg>
<p>Most active day: <%= current_user.most_active_day %></p>
<p>Highest very active minutes: <%= current_user.highest_very_active_minutes %> on <%= current_user.highest_very_active_date %></p>
<p>Least active day: <%= current_user.least_active_day %></p>

<h3>Sleep</h3>
<svg class="sleep-chart-stacked" width=960 height=400></svg>
<svg class="awakening-chart" width=960 height=400></svg>
<p>Average minutes asleep: <%= current_user.average_minutes_asleep %></p>
<p>Average minutes awake: <%= current_user.average_minutes_awake %></p>
<p>Average number of awakenings: <%= current_user.average_awakenings %></p>
<p>Average time in bed: <%= current_user.average_time_in_bed %></p>